name: cicd ec2 echo
on:
 push:
    branches:
       - main

jobs:
  echos-today:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v3
       - name: docker build
         uses: docker/setup-buildx-action@v2
       - name: docker build
         run: docker build -t echostoday:latest .
