name: cicd ec2 echo

on:
  push:
    branches:
      - main

jobs:
  echos-today:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build (local test only)
        run: docker build -t echostoday:latest .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_KEY }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/echo-today
            git pull origin main
            docker-compose -f echo.yaml up -d --build

    
